services:
  auth-service:
    ports:
      - "8080:8080"
      - "8081:8081"

  postgres:
    ports:
      - "5432:5432"

  redis:
    #ports:
      #- "6379:6379"

  prometheus:
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${PROJECT_ROOT}/deployments/prometheus/prometheus.dev.yaml:/etc/prometheus/prometheus.yml

  grafana:
    ports:
      - "3000:3000"

  loki:
    ports:
      - "3100:3100"

  alloy:
    ports:
      - "12345:12345"