services:
  auth-service:
    container_name: msginx-auth
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SERVICE_NAME=${APP_SERVICE_NAME}
      - APP_VERSION=${APP_VERSION}
      - HTTP_ADDR=${HTTP_ADDR}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_MIN_IDLE_CONNS=${REDIS_MIN_IDLE_CONNS}
      - REDIS_MAX_RETRIES=${REDIS_MAX_RETRIES}
      - REDIS_DIAL_TIMEOUT=${REDIS_DIAL_TIMEOUT}
      - REDIS_READ_TIMEOUT=${REDIS_READ_TIMEOUT}
      - REDIS_WRITE_TIMEOUT=${REDIS_WRITE_TIMEOUT}
      - REDIS_POOL_TIMEOUT=${REDIS_POOL_TIMEOUT}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:18.6-bookworm
    container_name: msginx-auth-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  go-migrations:
    image: migrate/migrate:4
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:8.2-bookworm
    container_name: msginx-auth-redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  prometheus:
    image: prom/prometheus:v3
    container_name: msginx-auth-prometheus
    volumes:
      - ${PROJECT_ROOT}/deployments/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana: 
    image: grafana/grafana:13.0
    container_name: msginx-auth-grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    volumes:
      - grafana_data:/var/lib/grafana
      - ${PROJECT_ROOT}/deployments/grafana/datasources:/etc/grafana/provisioning/datasources
      - ${PROJECT_ROOT}/deployments/grafana/dashboards:/etc/grafana/provisioning/dashboards

  loki:
    image: grafana/loki:3.7.0
    container_name: msginx-auth-loki
    command:
      - -config.file=/etc/loki/loki.yaml
    volumes:
      - ${PROJECT_ROOT}/deployments/loki/loki.yaml:/etc/loki/loki.yaml
      - loki_data:/loki

  alloy:
    image: grafana/alloy:v1.19.2
    container_name: msginx-auth-alloy
    command:
      - run
      - /etc/alloy/config.alloy
    volumes:
      - ${PROJECT_ROOT}/deployments/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
    depends_on:
      - loki

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  loki_data: